### ISSUE TITLE
August 29, 2022 Community Meeting

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/community#101]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by adambkaplan** [comment]
Follow ups from Beta API Workshop: https://hackmd.io/BsPjvGFwQgmVeJRe6FJfMA

**Comment by SaschaSchwarze0** [comment]
Our detect secrets is not complaining this:

```yaml
apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: some-build
spec:
  source:
    type: ContainerImage
    containerImage:
      image: ghcr.io/shipwright-io/sample-go/source-bundle:latest
      pullSecret: secret-1234
```

So, going without the `name` suffix should be fine.

<h1>🐜</h1>
