### ISSUE TITLE
Setup workflow to add new issues & pull requests to project automatically 

### ISSUE THREAD

**Issue by coreydaley** [shipwright-io/community#150]
To enable this workflow, we need to have an access token setup and added as a "secret" to the shipwright-io organization.

These instructions (https://github.com/marketplace/actions/add-to-github-projects#creating-a-pat-and-adding-it-to-your-repository) go over how to set it up. Please name the secret `ADD_TO_PROJECT_TOKEN`.

I have included the suggested workflow below, which will be included in the .github/workflows directory in reach repository. We will furnish this in our pull request to update them en mass.

```
name: Add issue or pull request to Project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/shipwright-io/projects/6
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
```
