### ISSUE TITLE
December 11th, 2023 Community Meeting 

### ISSUE THREAD

**Issue by qu1queee** [shipwright-io/community#180]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by SaschaSchwarze0** [comment]
API change on .spec.source.git.url to required. The [k8s sig-architecture documents that a change of a field from required to not and vice versa is considerer imcompatible](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#on-compatibility). Though, their documentation mainly talks about API calls (e. g. *Any API call (e.g. a structure POSTed to a REST endpoint) that succeeded before your change must succeed after your change.*) which means that the relevant part if the JSON/YAML serialized format and not the Go types.

With that, I suggest that we change it.

BTW, when creating this beta Build:

```yaml
apiVersion: shipwright.io/v1beta1
kind: Build
spec:
  source:
    git:
      cloneSecret: deploy-key
    type: Git
```

then the converted Alpha build is:

```yaml
apiVersion: shipwright.io/v1alpha1
kind: Build
spec:
  source:
    credentials:
      name: deploy-key
status:
  message: all validations succeeded
  reason: Succeeded
  registered: "True"
```

Both make no sense and it is probably a bug that we register it as successful. Running this build will run without source step.
