### ISSUE TITLE
[FEATURE] Support self-signed certificates in builds

### ISSUE THREAD

**Issue by diksha1999** [shipwright-io/community#258]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem or use-case? Please describe.

Shipwright builds are failing due to the issues while executing the first "source-default" step of ShipWright when a self-signed custom CA bundle is being used for a Git server. 
Scenarios:
1. Cloning source code from a private git server
2. Pulling container images from a private container registry
3. Pulling dependencies from a private repository (ex: Artifactory).

### Describe the solution that you would like.

Support for self-signed enterprise certificates in shipwright builds.

In enterprise environments, TLS certificates are often issued by a "corporate" certificate authority that is not globally trusted by RHEL. Actions that use HTTPS as transport (ex: cloning git source, pulling container images, downloading dependencies) need to be able to find and utilize the correct certificate authority.

### Anything else?
Related Openshift Builds epic link:
https://issues.redhat.com/browse/BUILD-1152

**Comment by bitgully** [comment]
@adambkaplan I was the one initially requesting this feature. An optional secret reference that @SaschaSchwarze0 mentioned would be sufficient. The integration with cert-manager might be nice to have but I would prefer not to create a mandatory dependency to another controller here.

**Comment by bitgully** [comment]
Having only one (global) trusted CA setting for the entire build sounds good to me. But it might make sense to still allow just adding additional certificates whilst keeping a default set of well-known public CAs.

**Comment by adambkaplan** [comment]
Thinking "big picture" here - I think we can inject CA bundles in a way that is general-purpose by extending the existing [Build Volumes](https://shipwright.io/docs/build/build/#defining-volumes) feature. Today the volumes + mount paths can only be defined at the `BuildStrategy` level. We could allow `Build` and `BuildRun` objects to define additional volumes that get injected into build containers.

The procedure could look like this:

1. Create a ConfigMap containing the TLS trust bundle to mount. This can be done by a user on their own, or with a tool like [trust-manager](https://cert-manager.io/docs/trust/trust-manager/):

   ```yaml
   kind: ConfigMap
   metadata:
     name: ca-trust-bundle
   data:
      ca-bundle.pem: |
        ------BEGIN CERTIFICATE------
        ...
   ```

2. In the `Build` object, add the volume (not specified in the build strategy!)

  ```yaml
   apiVersion: build.shipwright.io/v1beta1
   kind: Build
   metadata:
     ...
   spec:
     ...
     volumes:
       - name: ca-bundle
         configMap:
           name: ca-trust-bundle
         mountPath: /etc/pki/ca-trust/extracted # <--- This would be new!
   ```

3. When the build runs, it mounts the contents of `ca-trust-bundle` into _every_ container in the build pod, at the specified location.

This absolutely, 100% requires a SHIP for further discussion + refinement. This capability was originally called out as a "non-goal" in [SHIP-0022](https://github.com/shipwright-io/community/blob/main/ships/0022-build-strategy-volumes.md#non-goals), mainly to narrow the scope of the proposed feature. I think it's time to build on top of it.
